using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

// All of this was nabbed from https://www.youtube.com/watch?v=_lREXfAMUcE - Easy Enemy Healthbars in Unity
public class EnemyHealth : MonoBehaviour
{
    [SerializeField] private Slider slider;
#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
    private Camera camera;
#pragma warning restore CS0108 // Member hides inherited member; missing new keyword
    // Suppressed a warning CS0108 for "camera" in the line above - Assets\Scripts\Enemy\Healthbar\EnemyHealth.cs(10,37): warning CS0108: 'EnemyHealth.camera' hides inherited member 'Component.camera'. Use the new keyword if hiding was intended.
    // Weird pragma stuff generated by unity when I hit the supress. Documenting this in comments incase it becomes a problem later.
    [SerializeField] private Transform target;

    void Start()
    {
        camera = Camera.main;
    }

    public void UpdateHealthBar(float currentHealth, float maxHealth)
    {
        slider.value = currentHealth / maxHealth;
    }
    // Update is called once per frame
    void Update()
    {
        transform.rotation = camera.transform.rotation;
    }
}
